### ISSUE TITLE
scout:import broken by this change!

### ISSUE THREAD

**Issue by eminos** [typesense/laravel-scout-typesense-driver#45]
https://github.com/typesense/laravel-scout-typesense-driver/commit/0234cd8f00dd4b10b8355b23f874045d1e1fdae0

**Comment by karakhanyans** [comment]
Hi @eminos 

We are currently investigating the problem, could you please give us more details about this problem, as we are not able to reproduce in our end. 

We need your Laravel version, your PHP version.

Thanks.

**Comment by ricardo-lobo** [comment]
The problem is the usage of getDirty instead of getChanges

See https://github.com/laravel/framework/blob/78eb4dabcc03e189620c16f436358d41d31ae11f/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1126

After a model is updated, getDirty will always return empty and it will not be updated to Typesense.

Using latest Laravel version and PHP 8.1

**Comment by ricardo-lobo** [comment]
@eminos You are probably right. I haven't tested this to be sure. I noticed this yesterday because I have a test that checks if a product updated with certain fields is synced to Typesense.
